version: '3'

services:
  blogpy_postgresql:
    image: postgres:12
    container_name: blogpy_postgresql
    volumes:
      - webhook_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - webhook_network

volumes:
  webhook_postgresql:
    external: true
networks:
  webhook_network:
    external: true
